# Postchain configuration
messaging.privkey=872D0F412BDD00C01CE5C237360E7B67024F9FF250D96ED3154589E1DDDE9BA1
messaging.pubkey=0327F6EAE0B4A10B55051734179A0A5C5C3C4FA05E728594607E2B92096E29B405
messaging.port=9870
genesis.pubkey=0350FE40766BC0CE8D08B3F5B810E49A8352FDD458606BD5FAFE5ACDCDC8FF3F57
genesis.host=node0.devnet1.chromia.dev
genesis.port=9870
api.port=7740
database.driverclass=org.postgresql.Driver
database.username=postchain
database.password=postchain
database.url=jdbc:postgresql://172.17.0.1:5432/postchain
database.schema=snapshot_replica
infrastructure=net.postchain.d1.D1InfrastructureFactory
api.enable_tls=false
configuration.provider.node=managed
container.postgres_max_locks_per_transaction=1024
database.blockBuilderWriteConcurrency=100
database.readConcurrency=100
