<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>docker-images</artifactId>
        <groupId>net.postchain.images</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>

    <artifactId>chromia-server</artifactId>

    <properties>
        <main.class>net.postchain.server.AppKt</main.class>
        <image.name>chromaway/chromia-server</image.name>
    </properties>

    <dependencies>
        <!-- Docker image dependencies -->
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-server-cli</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-gtx</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>chromia-infrastructure</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <configuration>
                    <allowInsecureRegistries>false</allowInsecureRegistries>
                    <from>
                        <image>registry.gitlab.com/chromaway/core-tools/chromia-images/java17-quota:1.1.2@sha256:7bf5238d957d360cced7de89029d45ebb0056bcc24deb15639555c1582732d6e</image>
                    </from>
                    <container>
                        <appRoot>/opt/chromaway/postchain</appRoot>
                        <workingDirectory>/opt/chromaway/postchain</workingDirectory>
                        <mainClass>${main.class}</mainClass>
                        <jvmFlags>-XX:+CrashOnOutOfMemoryError</jvmFlags>
                        <environment>
                            <POSTCHAIN_DEBUG>false</POSTCHAIN_DEBUG>
                            <POSTCHAIN_RUNNING_IN_CONTAINER>true</POSTCHAIN_RUNNING_IN_CONTAINER>
                            <LOG4J_CONFIGURATION_FILE>/opt/chromaway/postchain/log4j2.yml</LOG4J_CONFIGURATION_FILE>
                        </environment>
                        <creationTime>${git.commit.time}</creationTime>
                        <filesModificationTime>${git.commit.time}</filesModificationTime>
                    </container>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
