<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>docker-images</artifactId>
        <groupId>net.postchain.images</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>

    <artifactId>chromia-server</artifactId>

    <properties>
        <main.class>net.postchain.server.AppKt</main.class>
        <image.name>chromaway/chromia-server</image.name>
        <project.build.scriptSourceDirectory>src/scripts</project.build.scriptSourceDirectory>
    </properties>

    <dependencies>
        <!-- Docker image dependencies -->
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-server-cli</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-web-static</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-gtx</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>chromia-infrastructure</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-eif-core</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <configuration>
                    <allowInsecureRegistries>false</allowInsecureRegistries>
                    <from>
                        <image>registry.gitlab.com/chromaway/core-tools/chromia-images/java21-quota:1.0.16@sha256:f9de057420265379b69d380c170d8a7d28b66610fed96f7a89abce0d04797b5f</image>
                    </from>
                    <container>
                        <appRoot>/opt/chromaway/postchain</appRoot>
                        <workingDirectory>/opt/chromaway/postchain</workingDirectory>
                        <mainClass>${main.class}</mainClass>
                        <jvmFlags>
                            <jvmFlag>-XX:+UnlockDiagnosticVMOptions</jvmFlag>
                            <jvmFlag>-XX:AbortVMOnException=java.lang.OutOfMemoryError</jvmFlag>
                        </jvmFlags>
                        <environment>
                            <POSTCHAIN_DEBUG>false</POSTCHAIN_DEBUG>
                            <POSTCHAIN_RUNNING_IN_CONTAINER>true</POSTCHAIN_RUNNING_IN_CONTAINER>
                            <LOG4J_CONFIGURATION_FILE>/opt/chromaway/postchain/log4j2.yml</LOG4J_CONFIGURATION_FILE>
                            <IMAGE_VERSION_TAG>${revision}</IMAGE_VERSION_TAG>
                        </environment>
                        <creationTime>${git.commit.time}</creationTime>
                        <filesModificationTime>${git.commit.time}</filesModificationTime>
                    </container>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>distro</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-assembly-plugin</artifactId>
                        <configuration>
                            <descriptors>
                                <descriptor>src/assembly/targz.xml</descriptor>
                            </descriptors>
                        </configuration>
                        <executions>
                            <execution>
                                <id>make-archive</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>single</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
