image: maven:3.8.4-jdk-11

.setup:
  before_script:
    - apt-get update && apt-get install -y docker.io
    - mkdir -p $HOME/.docker/cli-plugins/
    - wget -O $HOME/.docker/cli-plugins/docker-buildx $BUILDX_URL
    - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
    - export POSTCHAIN_TEST_MASTER_HOST=$(hostname -I | awk '{print $1}') # Finds the IP of the build job container
    - mkdir -p $TEST_MOUNT_DIRECTORY
    - docker buildx create --use --name postchain-builder --platform linux/amd64,linux/arm64,linux/arm/v8
    - docker image pull registry.gitlab.com/chromaway/postchain-distribution/chromaway/postchain-server:3.7.0-SNAPSHOT
    - docker image pull registry.gitlab.com/chromaway/postchain-distribution/chromaway/postchain-subnode:3.7.0-SNAPSHOT
    - docker image pull registry.gitlab.com/chromaway/postchain-distribution/chromaway/postgres:3.7.0-SNAPSHOT
  artifacts:
    when: on_failure
    paths:
      - "**/*.log"
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"
        - "*/target/failsafe-reports/TEST-*.xml"
    expire_in: 1 week

.git_template: &git_setup |
  git remote set-url --push origin "https://oauth2:${BUILD_USER_GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
  git config user.name "build-user core-dev"
  git config user.email build_user@chromaway.com

stages:
  - docs
  - build
  - deploy
  - release

docs:
  image: python
  stage: docs
  artifacts:
    paths:
      - '**/_doc'
  only:
    - dev
    - master
    - /^support\/.*$/
  before_script:
    - pip install sphinx sphinx-rtd-theme
  script:
    - sphinx-build -c doc/enterprise0 -b html doc/source directory1-example/_doc

deploy:
  extends: .setup
  stage: deploy
  dependencies:
    - docs
  only:
    - dev
    - master
    - /^support\/.*$/
  script:
    - mvn $MAVEN_CLI_OPTS --activate-profiles ci,distro deploy

build:
  extends: .setup
  stage: build
  except:
    - dev
    - master
    - tags
    - /^support\/.*$/
  script:
    - mvn $MAVEN_CLI_OPTS --activate-profiles ci verify -Dtest=Directory1DeploymentIT -DfailIfNoTests=false

release:
  stage: release
  script:
    - *git_setup
    - git fetch --tags
    - LATEST_VERSION_TAG=$(git for-each-ref --sort=-version:refname --count=1 --format="%(refname:short)" refs/tags)
    - mvn -B gitflow:support-start -DskipTestProject=true -DtagName=$LATEST_VERSION_TAG
    - git checkout $CI_COMMIT_REF_NAME
    - DIGIT="${VERSION_DIGIT_TO_INCREMENT:-1}"
    - mvn -B gitflow:release -DskipTestProject=true -DversionDigitToIncrement=$DIGIT
  only:
    - dev
  when: manual

patch-start:
  stage: release
  script:
    - *git_setup
    - git checkout $CI_COMMIT_REF_NAME
    - mvn -B gitflow:hotfix-start -DfromBranch=$CI_COMMIT_REF_NAME
    - git push origin HEAD
  only:
    - master
    - /^support\/.*$/
  when: manual

patch-finish:
  stage: release
  script:
    - *git_setup
    - git checkout $CI_COMMIT_REF_NAME
    - mvn -B gitflow:hotfix-finish -DskipTestProject=true -DhotfixBranch=$CI_COMMIT_REF_NAME -DversionDigitToIncrement=2
  only:
    - /^hotfix\/.*$/
  when: manual

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -s .gitlab-settings.xml -U"
  # Configure postgres service (https://hub.docker.com/_/postgres/)
  POSTGRES_DB: postchain
  POSTGRES_USER: postchain
  POSTGRES_PASSWORD: postchain
  POSTCHAIN_DB_URL: jdbc:postgresql://postgres/postchain
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: tcp://docker:2375
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2
  DOCKER_CLI_EXPERIMENTAL: enabled
  BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
  TEST_MOUNT_DIRECTORY: /builds/$CI_PROJECT_PATH/mnt
  # The test Directory1DeploymentIT (postchain-images/managed-mode/directory1/) often consume more disk so we don't have 2GB free, therefore we remove the check to avoid failing.
  TESTCONTAINERS_CHECKS_DISABLE: "true"

services:
  - postgres
  - name: docker:20-dind
    alias: docker
    # explicitly disable tls to avoid docker startup interruption
    command: [ "--tls=false" , "--experimental"]

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository
