ignore:
  # snakeyaml
  - vulnerability: GHSA-mjmj-j48q-9wg2
  - vulnerability: CVE-2024-24790   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2023-29405   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2023-29404   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2023-29402   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2023-24540   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2023-24538   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2023-24531   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2024-24791   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2024-24784   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2023-45288   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2023-45287   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2023-45285   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2023-44487   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2023-39323   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2023-29403   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2023-29400   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2023-24539   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2023-24537   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2023-24536   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2023-24534   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2022-41725   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2022-41724   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2022-41723   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2022-41722   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2022-41715   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2022-32189   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2022-30635   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2022-30633   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2022-30632   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2022-30631   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2022-30630   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2022-30580   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2022-2880    # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2022-2879    # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2022-28131   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
  - vulnerability: CVE-2022-27664   # False-positive in gosu, see https://github.com/tianon/gosu/blob/master/SECURITY.md
