version: '3.1'

services:

  postgres:
    image: chromaway/postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postchain

  postchain0:
    image: chromaway/postchain-server
    ports:
      - "7740:7740"
      - "50050:50051"
    depends_on:
      - postgres
    volumes:
      - ./config:/config
    environment:
      POSTCHAIN_DB_URL: jdbc:postgresql://postgres/postchain
      POSTCHAIN_CONFIG: /config/config.0.properties
      POSTCHAIN_INITIAL_CHAIN_IDS: 0
  postchain1:
    image: chromaway/postchain-server
    ports:
      - "7741:7741"
      - "50051:50051"
    depends_on:
      - postgres
    volumes:
      - ./config:/config
    environment:
      POSTCHAIN_DB_URL: jdbc:postgresql://postgres/postchain
      POSTCHAIN_CONFIG: /config/config.1.properties
      POSTCHAIN_INITIAL_CHAIN_IDS: 0
  postchain2:
    image: chromaway/postchain-server
    ports:
      - "7742:7742"
      - "50052:50051"
    depends_on:
      - postgres
    volumes:
      - ./config:/config
    environment:
      POSTCHAIN_DB_URL: jdbc:postgresql://postgres/postchain
      POSTCHAIN_CONFIG: /config/config.0.properties
      POSTCHAIN_INITIAL_CHAIN_IDS: 0

volumes:
  pgdata:
