<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>docker-images</artifactId>
        <groupId>net.postchain.images</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>

    <artifactId>chromia-subnode</artifactId>

    <properties>
        <image.name>chromaway/chromia-subnode</image.name>
    </properties>

    <dependencies>
        <!-- Docker image dependencies -->
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-server-cli</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain.rell</groupId>
            <artifactId>rell-gtx</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>chromia-infrastructure</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-eif-core</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <configuration>
                    <allowInsecureRegistries>false</allowInsecureRegistries>
                    <from>
                        <image>registry.gitlab.com/chromaway/core-tools/chromia-images/java21-postgres14:1.0.1@sha256:b7edcb214ca985db20bf4a5247937b0e7dd3128c1a24559ee9f4f688af6f62fc</image>
                    </from>
                    <container>
                        <appRoot>/opt/chromaway/postchain</appRoot>
                        <workingDirectory>/opt/chromaway/postchain</workingDirectory>
                        <entrypoint>/bin/bash</entrypoint>
                        <args>entrypoint.sh</args>
                        <environment>
                            <POSTCHAIN_RUNNING_IN_CONTAINER>true</POSTCHAIN_RUNNING_IN_CONTAINER>
                            <LOG4J_CONFIGURATION_FILE>/opt/chromaway/postchain/log4j2.yml</LOG4J_CONFIGURATION_FILE>
                            <POSTCHAIN_DIR>/opt/chromaway/postchain</POSTCHAIN_DIR>
                            <POSTGRES_DB>postchain</POSTGRES_DB>
                            <POSTGRES_USER>postchain</POSTGRES_USER>
                            <POSTGRES_PASSWORD>postchain</POSTGRES_PASSWORD>
                            <POSTGRES_INITDB_ARGS>"--lc-collate=C.UTF-8 --lc-ctype=C.UTF-8 --encoding=UTF-8"</POSTGRES_INITDB_ARGS>
                        </environment>
                        <creationTime>${git.commit.time}</creationTime>
                        <filesModificationTime>${git.commit.time}</filesModificationTime>
                    </container>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
