# Copyright (c) 2017 ChromaWay Inc. See README for license information.

# Configurations
configuration.provider.node=managed
infrastructure=net.postchain.managed.Chromia0InfrastructureFactory

# Storage
database.driverclass=org.postgresql.Driver
database.url=jdbc:postgresql://host.docker.internal:5432/postchain
database.username=postchain
database.password=postchain

# The Rest API will listen on this port.
# unset: Default port 7740 will be used
# -1: no API will be started
# 0: Assign any free port. Check the console output to find the actual port used
# >0: Force a certain port
api.port=-1
