# Copyright (c) 2022 ChromaWay Inc. See README for license information.
ARG postchain_server_image
FROM $postchain_server_image

ARG postchain_dir=/opt/chromaway/postchain
COPY target/lib $postchain_dir/lib
