# Copyright (c) 2022 ChromaWay Inc. See README for license information.
FROM registry.gitlab.com/chromaway/postchain-distribution/chromaway/postchain-server:3.7.0-SNAPSHOT

ARG postchain_dir=/opt/chromaway/postchain
COPY target/lib $postchain_dir/lib
