<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>postchain-chromia</artifactId>
        <groupId>net.postchain</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>

    <modules>
        <module>directory1</module>
    </modules>

    <groupId>net.postchain.chain0</groupId>
    <artifactId>chain0-impl</artifactId>
    <name>Chain0 - Parent</name>
    <description>Parent module for chain0 implementations</description>

    <properties>
        <revision>dev</revision>

        <rell.directory>${project.parent.basedir}/rell</rell.directory>
        <rellCompileModules>management_chain_testnet,anchoring_chain_system,anchoring_chain_cluster,icmf,iccf</rellCompileModules>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-maven-plugin</artifactId>
                <inherited>false</inherited>
                <configuration>
                    <source>${project.basedir}/rell/src</source>
                </configuration>
                <executions>
                    <execution>
                        <id>rell-compile</id>
                        <goals>
                            <goal>rell-compile</goal>
                        </goals>
                        <configuration>
                            <mainModule>${rellCompileModules}</mainModule>
                        </configuration>
                    </execution>
                    <execution>
                        <id>rell-integration-test</id>
                        <goals>
                            <goal>rell-integration-test</goal>
                        </goals>
                        <configuration>
                            <skip>${skipTests}</skip>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>make-archive</id>
                            <phase>package</phase>
                            <goals>
                                <goal>single</goal>
                            </goals>
                            <configuration>
                                <descriptors>
                                    <descriptor>src/assembly/targz.xml</descriptor>
                                </descriptors>
                            </configuration>
                        </execution>
                        <execution>
                            <id>make-executable-jar</id>
                            <phase>none</phase>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
