package net.postchain.mc.cli.util

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.groups.mutuallyExclusiveOptions
import com.github.ajalt.clikt.parameters.groups.required
import com.github.ajalt.clikt.parameters.groups.single
import com.github.ajalt.clikt.parameters.options.OptionTransformContext
import com.github.ajalt.clikt.parameters.options.convert
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.defaultLazy
import com.github.ajalt.clikt.parameters.options.flag
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.options.switch
import com.github.ajalt.clikt.parameters.options.validate
import com.github.ajalt.clikt.parameters.types.long
import net.postchain.chain0.model.ProviderQuotaType
import net.postchain.client.config.PostchainClientConfig
import net.postchain.client.impl.PostchainClientImpl
import net.postchain.common.hexStringToByteArray
import net.postchain.crypto.PubKey
import net.postchain.mc.cli.base.CommandBase
import net.postchain.mc.cli.base.NAME_LENGTH_MAX
import net.postchain.mc.cli.config.PmcConfigProvider.fromSystemConfig


const val POSTCHAIN_CLIENT_CONFIG = "POSTCHAIN_CLIENT_CONFIG"
fun CliktCommand.pubkeyOption(helpMsg: String = "Public key") = option("-pk", "--pubkey", help = helpMsg, envvar = "POSTCHAIN_PUBKEY")
        .convert { PubKey(it) }

fun CliktCommand.configOption() = configOptionBase().defaultLazy { fromSystemConfig() }
fun CliktCommand.clientOption() = clientOptionBase()
        .defaultLazy { PostchainClientImpl(fromSystemConfig()) }

fun CliktCommand.nopClientOption() = clientOptionBase()
        .convert { NopPostchainClient(it) }
        .defaultLazy { NopPostchainClient(PostchainClientImpl(fromSystemConfig())) }

private fun CliktCommand.clientOptionBase() = configOptionBase()
        .convert { PostchainClientImpl(it) }

private fun CliktCommand.configOptionBase() =
        option("-cfg", "--config", help = "Configuration file for PMC (overrides system configuration)", envvar = POSTCHAIN_CLIENT_CONFIG)
                .convert { PostchainClientConfig.fromProperties(it) }

fun CliktCommand.nameOption(helpMessage: String) = option("-n", "--name", help = helpMessage)

fun CliktCommand.nameOrGenerateOption(helpMessage: String) = mutuallyExclusiveOptions(
        nameOption(helpMessage).validate(validateAlphaNumeric()),
        option(
                "-a", "--auto-generate-name",
                help = "Set if ${helpMessage.lowercase()} should be autogenerated (suppressed by -n)"
        ).flag().convert {
            if (it) {
                CommandBase.autoGenerateName()
            } else null
        }
).single().required()

fun validateAlphaNumeric(): OptionTransformContext.(String) -> Unit =
        {
            require(CommandBase.isAlphanumeric(it)) { "Name must be alphanumeric" }
            require(it.length <= NAME_LENGTH_MAX) { "Name is too long, maximum allowed length is $NAME_LENGTH_MAX" }
        }

sealed class VoterSetOrPubkeysOption(val data: String) {
    class Pubkeys(data: String) : VoterSetOrPubkeysOption(data) {
        val pubkeys get() = data.split(",").map { it.hexStringToByteArray() }
    }

    class VoterSet(data: String) : VoterSetOrPubkeysOption(data)

}

fun CliktCommand.pubkeysOrVotersetOption() = mutuallyExclusiveOptions(
        option("--voter-set", help = "Name of voter set").convert { VoterSetOrPubkeysOption.VoterSet(it) },
        option("--pubkeys", help = "Comma delimited list of public keys").convert { VoterSetOrPubkeysOption.Pubkeys(it) }
).single().required()

fun CliktCommand.maxBlockchainsOption() = option("-mb", "--max-blockchains", help = "Max number of blockchains per container").long()

const val cpuOptionHelp = "CPU limit (percent of cpus, 10 == 0.1 cpu(s), 150 == 1.5 cpu(s))"
const val ramOptionHelp = "RAM limit (Mb)"
const val storageOptionHelp = "Storage limit (Mb)"

fun CliktCommand.providerTierOption() = option(help = "Provider tier (default: -cnp)").switch(
        "-cnp" to ProviderType.COMMUNITY_NODE_PROVIDER,
        "-np" to ProviderType.NODE_PROVIDER,
        "-sp" to ProviderType.SYSTEM_PROVIDER
).default(ProviderType.COMMUNITY_NODE_PROVIDER)

fun CliktCommand.providerQuotaTypeOption() = option(help = "Provider quota type").switch(
        "-ma" to ProviderQuotaType.max_actions_per_day,
        "-mc" to ProviderQuotaType.max_containers
)

fun CliktCommand.proposalMessageOption(helpMessage: String = "Proposal message") = option("-m", "--message", help = helpMessage)
        .default("")