package net.postchain.mc.cli.util

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.groups.mutuallyExclusiveOptions
import com.github.ajalt.clikt.parameters.groups.required
import com.github.ajalt.clikt.parameters.groups.single
import com.github.ajalt.clikt.parameters.options.*
import net.postchain.client.config.PostchainClientConfig
import net.postchain.client.core.ConcretePostchainClient
import net.postchain.mc.cli.base.CommandBase
import net.postchain.mc.cli.base.NAME_LENGTH_MAX


fun CliktCommand.configOption() = configOptionBase().required()
fun CliktCommand.clientOption() = clientOptionBase().required()

fun CliktCommand.nopClientOption() = clientOptionBase()
    .convert { NopPostchainClient(it) }
    .required()

private fun CliktCommand.clientOptionBase() = configOptionBase()
    .convert { ConcretePostchainClient(it) }

private fun CliktCommand.configOptionBase() =
    option("-cfg", "--config", help = "Configuration file for CLI", envvar = "POSTCHAIN_CLIENT_CONFIG")
        .convert { PostchainClientConfig.fromProperties(it) }

fun CliktCommand.nameOption(helpMessage: String) = option("-n", "--name", help = helpMessage)

fun CliktCommand.nameOrGenerateOption(helpMessage: String) = mutuallyExclusiveOptions(
    nameOption(helpMessage).validate(validateAlphaNumeric()),
    option(
        "-a", "--auto-generate-name",
        help = "Set if ${helpMessage.lowercase()} should be autogenerated (suppressed by -n)"
    ).flag().convert {
        if (it) {
            CommandBase.autoGenerateName()
        } else null
    }
).single().required()

fun validateAlphaNumeric(): OptionTransformContext.(String) -> Unit =
    {
        require(CommandBase.isAlphanumeric(it)) { "Name must be alphanumeric" }
        require(it.length <= NAME_LENGTH_MAX) { "Name is too long, maximum allowed length is $NAME_LENGTH_MAX" }
    }
