<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>chain0-impl</artifactId>
        <groupId>net.postchain.chain0</groupId>
        <version>3.7.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>

    <artifactId>directory1</artifactId>
    <name>Chain0 - D1/C1</name>
    <description>Chain0 implementations for Directory1/Chromia1</description>

    <properties>
        <rellTestModules>common</rellTestModules>
    </properties>

    <dependencies>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-gtv</artifactId>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-client</artifactId>
        </dependency>
    </dependencies>
    <pluginRepositories>
        <pluginRepository>
            <id>rellmaven</id>
            <url>https://gitlab.com/api/v4/projects/37668820/packages/maven</url>
        </pluginRepository>
    </pluginRepositories>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-maven-plugin</artifactId>
                <version>0.4.3</version>
                <configuration>
                    <source>src/main/rell</source>
                    <packageName>net.postchain.chain0</packageName>
                </configuration>
                <executions>
                    <execution>
                        <id>rell-test</id>
                        <goals>
                            <goal>rell-test</goal>
                        </goals>
                        <configuration>
                            <testModule>${rellTestModules}</testModule>
                            <skip>${skipTests}</skip>
                            <dbUrl>jdbc:postgresql://${postgres.host}/postchain?user=postchain&amp;username=postchain&amp;password=postchain&amp;schema=${rell.main.module}</dbUrl>
                        </configuration>
                    </execution>
                    <execution>
                        <id>rell-client-gen</id>
                        <goals>
                            <goal>rell-generate-client</goal>
                        </goals>
                        <configuration>
                            <mainModules>
                                <mainModule>directory1</mainModule>
                                <mainModule>chromia1</mainModule>
                            </mainModules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
