<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>postchain-chromia</artifactId>
        <groupId>net.postchain</groupId>
        <version>3.9.4</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>deployment-test</artifactId>

    <dependencies>
        <dependency> <!-- Ensure build order -->
            <groupId>net.postchain</groupId>
            <artifactId>pmc-directory</artifactId>
            <version>${project.version}</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>
        <dependency> <!-- Ensure build order -->
            <groupId>net.postchain.images</groupId>
            <artifactId>admin-client</artifactId>
            <version>3.9.4</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>
        <dependency> <!-- Ensure build order -->
            <groupId>net.postchain.images</groupId>
            <artifactId>chromia-server</artifactId>
            <version>3.9.4</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>
        <dependency> <!-- Ensure build order -->
            <groupId>net.postchain.images</groupId>
            <artifactId>chromia-subnode</artifactId>
            <version>3.9.4</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
        </dependency>

        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-admin-client-cli</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>jdbc</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit-pioneer</groupId>
            <artifactId>junit-pioneer</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-coroutines-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.awaitility</groupId>
            <artifactId>awaitility-kotlin</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mandas</groupId>
            <artifactId>docker-client</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.willowtreeapps.assertk</groupId>
            <artifactId>assertk</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>

        <testResources>
            <testResource>
                <filtering>false</filtering>
                <directory>${project.build.directory}/chain0</directory>
            </testResource>
            <testResource>
                <directory>src/test/resources</directory>
            </testResource>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/pom.properties</include>
                </includes>
            </testResource>
        </testResources>
        <plugins>
            <plugin>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>rell-client-gen</id>
                        <goals>
                            <goal>rell-generate-client</goal>
                        </goals>
                        <configuration>
                            <source>${project.parent.basedir}/chain0-impl/rell/src</source>
                            <packageName>net.postchain.chain0</packageName>
                            <mainModules>
                                <mainModule>anchoring_chain_common</mainModule>
                            </mainModules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default</id>
                        <phase>none</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>ci</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>integration-test</id>
                                <phase>integration-test</phase>
                                <goals>
                                    <goal>integration-test</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>verify</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>win</id>
            <activation>
                <os>
                    <family>Windows</family>
                    <arch>x86</arch>
                </os>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <configuration>
                            <systemPropertyVariables>
                                <DOCKER_HOST_MASTER>172.17.0.1</DOCKER_HOST_MASTER>
                            </systemPropertyVariables>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>macos</id>
            <activation>
                <os>
                    <family>mac</family>
                </os>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <configuration>
                            <systemPropertyVariables>
                                <DOCKER_HOST_MASTER>host.docker.internal</DOCKER_HOST_MASTER>
                            </systemPropertyVariables>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
