<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>postchain-chromia</artifactId>
        <groupId>net.postchain</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>deployment-test</artifactId>

    <dependencies>
        <dependency> <!-- Ensure build order -->
            <groupId>net.postchain.images</groupId>
            <artifactId>chromia-server</artifactId>
            <version>${revision}</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>
        <dependency> <!-- Ensure build order -->
            <groupId>net.postchain.images</groupId>
            <artifactId>chromia-subnode</artifactId>
            <version>${revision}</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>directory-chain</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-eif-contracts</artifactId>
            <version>${eif.version}</version>
            <classifier>sources</classifier>
            <scope>provided</scope>
            <type>tar.gz</type>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-eif-rell</artifactId>
            <version>${eif.version}</version>
            <classifier>sources</classifier>
            <scope>provided</scope>
            <type>tar.gz</type>
        </dependency>

        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
        </dependency>

        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>jdbc</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- Needed for testcontainers -->
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit-pioneer</groupId>
            <artifactId>junit-pioneer</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-coroutines-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.awaitility</groupId>
            <artifactId>awaitility-kotlin</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mandas</groupId>
            <artifactId>docker-client</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.willowtreeapps.assertk</groupId>
            <artifactId>assertk-jvm</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>

        <testResources>
            <testResource>
                <filtering>false</filtering>
                <directory>${project.build.directory}/chain0</directory>
            </testResource>
            <testResource>
                <directory>src/test/resources</directory>
            </testResource>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>**/pom.properties</include>
                </includes>
            </testResource>
        </testResources>

        <plugins>
            <!-- Unpack dependencies: EIF rell code and EIF contracts -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>unpack-eif</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>unpack-dependencies</goal>
                        </goals>
                        <configuration>
                            <classifier>sources</classifier>
                            <includeArtifactIds>postchain-eif-rell</includeArtifactIds>
                            <includeTypes>tar.gz</includeTypes>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                        </configuration>
                    </execution>
                    <execution>
                        <id>unpack-contracts</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>unpack-dependencies</goal>
                        </goals>
                        <configuration>
                            <classifier>sources</classifier>
                            <includeArtifactIds>postchain-eif-contracts</includeArtifactIds>
                            <includeTypes>tar.gz</includeTypes>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Collect rell code to compile -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>generate-test-resources</phase>
                        <configuration>
                            <outputDirectory>${project.build.directory}/rell/src</outputDirectory>
                            <resources>
                                <!-- Source code of test dapps -->
                                <resource>
                                    <directory>${project.basedir}/rell/src</directory>
                                </resource>
                                <!-- Source code of D1 components needed for test dapps -->
                                <resource>
                                    <directory>${maven.multiModuleProjectDirectory}/${directory.source}</directory>
                                    <includes>
                                        <include>messaging/icmf/module.rell</include>
                                        <include>messaging/icmf/constants.rell</include>
                                        <include>iccf/module.rell</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Compile D1 and test dapps -->
            <plugin>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>install-eif-libs</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>rell-install</goal>
                        </goals>
                        <configuration>
                            <source>${project.build.directory}/postchain-eif-rell/rell/src</source>
                            <configPath>${project.build.directory}/postchain-eif-rell/rell/chromia.yml</configPath>
                        </configuration>
                    </execution>
                    <execution>
                        <id>rell-d1-client-gen</id>
                        <goals>
                            <goal>rell-generate-client</goal>
                        </goals>
                        <configuration>
                            <packageName>net.postchain.chain0</packageName>
                            <mainModules>
                                <mainModule>management_chain_directory1</mainModule>
                                <mainModule>anchoring_chain_common</mainModule>
                                <mainModule>management_chain_mainnet</mainModule>
                                <mainModule>economy_chain</mainModule>
                            </mainModules>
                        </configuration>
                    </execution>
                    <execution>
                        <id>rell-eif-client-gen</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>rell-generate-client</goal>
                        </goals>
                        <configuration>
                            <packageName>net.postchain.eif</packageName>
                            <source>${project.build.directory}/postchain-eif-rell/rell/src</source>
                            <target>${project.build.directory}/generated-sources/rell-client/eif</target>
                            <force>true</force>
                            <mainModules>
                                <mainModule>tests.hbridge_it</mainModule>
                                <mainModule>transaction_submitter</mainModule>
                            </mainModules>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile-d1</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>rell-compile</goal>
                        </goals>
                        <configuration>
                            <rootFolder>${project.basedir}/..</rootFolder>
                            <configFile>deployment-test/src/test/resources/net/postchain/images/directory1/directory1.yml</configFile>
                            <source>${directory.source}</source>
                            <target>deployment-test/target/test-classes/directory1deployment</target>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile-test-dapps</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>rell-compile</goal>
                        </goals>
                        <configuration>
                            <rootFolder>${project.basedir}/..</rootFolder>
                            <configFile>deployment-test/rell/config.yml</configFile>
                            <source>deployment-test/target/rell/src</source>
                            <target>deployment-test/target/test-classes/directory1deployment</target>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile-eif-chains</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>rell-compile</goal>
                        </goals>
                        <configuration>
                            <rootFolder>${project.basedir}/..</rootFolder>
                            <configFile>deployment-test/src/test/resources/net/postchain/images/directory1/eif.yml</configFile>
                            <source>deployment-test/target/postchain-eif-rell/rell/src</source>
                            <target>deployment-test/target/test-classes/directory1deployment</target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- EIF / contracts / add source and resources -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <id>add-test-source</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>add-test-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>target/generated-test-sources</source>
                            </sources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>add-test-resource</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>add-test-resource</goal>
                        </goals>
                        <configuration>
                            <resources>
                                <resource>
                                    <directory>
                                        target/postchain-eif-contracts
                                    </directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- EIF / contracts / generate abi and java stubs -->
            <plugin>
                <groupId>com.github.longdt</groupId>
                <artifactId>web3j-maven-plugin</artifactId>
                <version>4.8.10</version>
                <configuration>
                    <packageName>net.postchain.eif.contracts</packageName>
                    <nativeJavaType>false</nativeJavaType>
                    <contract>
                        <includes>
                            <include>TokenBridge</include>
                            <include>TestToken</include>
                            <include>Validator</include>
                            <include>Anchoring</include>
                            <include>ManagedValidator</include>
                            <include>DirectoryChainValidator</include>
                        </includes>
                    </contract>
                    <pathPrefixes>
                        <pathPrefix>@openzeppelin=../node_modules/@openzeppelin</pathPrefix>
                    </pathPrefixes>
                    <abiSourceFiles>
                        <directory>${project.build.directory}/postchain-eif-contracts/abi</directory>
                        <includes>
                            <include>**/TokenBridge.json</include>
                            <include>**/TestToken.json</include>
                            <include>**/Validator.json</include>
                            <include>**/Anchoring.json</include>
                            <include>**/ManagedValidator.json</include>
                            <include>**/DirectoryChainValidator.json</include>
                        </includes>
                    </abiSourceFiles>
                    <outputDirectory>
                        <abi>${project.basedir}/target/generated-test-resources</abi>
                        <java>${project.basedir}/target/generated-test-sources</java>
                    </outputDirectory>
                    <outputFormat>java,abi</outputFormat>
                </configuration>
                <executions>
                    <execution>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>generate-sources</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- /EIF -->

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default</id>
                        <phase>none</phase>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.0.2</version>
                <executions>
                  <execution>
                    <goals>
                      <goal>test-jar</goal>
                    </goals>
                  </execution>
                </executions>
              </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>ci</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>integration-test</id>
                                <phase>integration-test</phase>
                                <goals>
                                    <goal>integration-test</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>verify</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>win</id>
            <activation>
                <os>
                    <family>Windows</family>
                    <arch>x86</arch>
                </os>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <configuration>
                            <systemPropertyVariables>
                                <DOCKER_HOST_MASTER>172.17.0.1</DOCKER_HOST_MASTER>
                            </systemPropertyVariables>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>macos</id>
            <activation>
                <os>
                    <family>mac</family>
                </os>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <configuration>
                            <systemPropertyVariables>
                                <DOCKER_HOST_MASTER>host.docker.internal</DOCKER_HOST_MASTER>
                            </systemPropertyVariables>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
