<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>postchain-chromia</artifactId>
        <groupId>net.postchain</groupId>
        <version>3.9.1-eif</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>docker-images</artifactId>
    <groupId>net.postchain.images</groupId>
    <packaging>pom</packaging>
    <modules>
        <module>admin-client</module>
        <module>chromia-server</module>
        <module>chromia-subnode</module>
        <module>postchain-mc</module>
    </modules>

    <properties>
        <!--suppress UnresolvedMavenProperty -->
        <gitlab.username>${CI_REGISTRY_USER}</gitlab.username>
        <!--suppress UnresolvedMavenProperty -->
        <gitlab.password>${CI_REGISTRY_PASSWORD}</gitlab.password>
        <gitlab.registry>registry.gitlab.com/chromaway/postchain-chromia</gitlab.registry>
        <docker.cache>/tmp/docker-cache</docker.cache>
        <image.platforms>linux/amd64,linux/arm64</image.platforms>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>io.fabric8</groupId>
                    <artifactId>docker-maven-plugin</artifactId>
                    <version>0.40.2</version>
                    <configuration>
                        <images>
                            <image>
                                <!--suppress UnresolvedMavenProperty -->
                                <name>${image.name}:latest</name>
                                <build>
                                    <contextDir>${project.basedir}</contextDir>
                                    <filter>@</filter>
                                </build>
                            </image>
                        </images>
                    </configuration>
                    <executions>
                        <execution>
                            <id>docker:build</id>
                            <phase>package</phase>
                            <goals>
                                <goal>build</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <profiles>
        <profile>
            <id>gitlab-registry</id>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <!-- We are using custom maven executions instead of i.e. fabric8 docker-maven-plugin since v0.38.1 does NOT support building to multiple architectures. When they do, feel free to replace this plugin again -->
                            <groupId>org.codehaus.mojo</groupId>
                            <artifactId>exec-maven-plugin</artifactId>
                            <executions>
                                <execution>
                                    <id>docker-login</id>
                                    <phase>prepare-package</phase>
                                    <goals>
                                        <goal>exec</goal>
                                    </goals>
                                    <configuration>
                                        <executable>docker</executable>
                                        <arguments>
                                            <argument>login</argument>
                                            <argument>registry.gitlab.com</argument>
                                            <argument>-u</argument>
                                            <argument>${env.CI_REGISTRY_USER}</argument>
                                            <argument>-p</argument>
                                            <argument>${env.CI_REGISTRY_PASSWORD}</argument>
                                        </arguments>
                                    </configuration>
                                </execution>
                                <execution>
                                    <id>build-image</id>
                                    <phase>package</phase>
                                    <goals>
                                        <goal>exec</goal>
                                    </goals>
                                    <configuration>
                                        <executable>docker</executable>
                                        <arguments>
                                            <argument>buildx</argument>
                                            <argument>build</argument>
                                            <argument>--platform</argument>
                                            <argument>${image.platforms}</argument>
                                            <argument>--tag</argument>
                                            <argument>${gitlab.registry}/${image.name}:${project.version}-${postchain.eif.version}
                                            </argument>
                                            <argument>${project.basedir}/.</argument>
                                            <argument>--push</argument>
                                        </arguments>
                                    </configuration>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
    </profiles>

</project>