Configuration:
  name: Default
  monitorInterval: 30 # sec.

  Properties:
    Property:
    - name: logs
      value: "logs"
    - name: filename
      value: "postchain"
    - name: fileExt
      value: "log"

  Appenders:
    Console:
      name: ConsoleAppender
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "%-5level %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} -%notEmpty{ [%notEmpty{bc-rid=%.-2X{blockchainRID}:%.4X{blockchainRID}}%notEmpty{, chain-id=%X{chainIID}}]:} %msg%n"
    RollingFile:
      name: FileAppender
      fileName: "${logs}/${filename}.${fileExt}"
      filePattern: "${logs}/${filename}-%d{yyyy-MM-dd-HH-mm}.%i.${fileExt}.gz"
      Policies:
        TimeBasedTriggeringPolicy:
          interval: 60
          modulate: true
        SizeBasedTriggeringPolicy:
          size: 10 MB
      DefaultRolloverStrategy:
        max: 100
        delete:
          basePath: "${logs}"
          IfFileName:
            glob: "${filename}*${fileExt}.gz"
          IfAccumulatedFileSize:
            exceeds: 100 MB
      PatternLayout:
        pattern: "%-5level %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} --%notEmpty{ [%notEmpty{bc-rid=%.-2X{blockchainRID}:%.4X{blockchainRID}}%notEmpty{, chain-id=%X{chainIID}}]:} %msg%n"

  Loggers:

    Root:
      level: warn
      AppenderRef:
      - ref: ConsoleAppender
      - ref: FileAppender

    Logger:

    - name: net.postchain.api.rest.controller
      level: warn
      additivity: false

    - name: net.postchain
      level: info
      additivity: false
      AppenderRef:
      - ref: ConsoleAppender
      - ref: FileAppender
