package net.postchain.mc.cli.cluster

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.options.*
import net.postchain.cli.util.nodeConfigOption
import net.postchain.mc.cli.base.CliError
import net.postchain.mc.cli.base.CommandBase.Companion.autoGenerateName
import net.postchain.mc.cli.cluster.util.clusterNameOption
import net.postchain.mc.cli.cluster.util.validateAlphaNumeric
import net.postchain.mc.cli.common0.CliExecution
import net.postchain.mc.config.app.BaseClientConfig

class CommandAddCluster : CliktCommand(
    name = "add-cluster",
    help = "Create a new cluster that can hold containers with blockchains."
) {

    private val nodeConfig by nodeConfigOption()

    private val name by clusterNameOption().validate(validateAlphaNumeric())
    private val autoGenerateClusterName by option(
        "-a", "--auto-generate-name",
        help = "Set if cluster name should be autogenerated (suppressed by -n)"
    ).flag().convert {
        if (it) {
            autoGenerateName()
        } else null
    }

    private val providers by option(
        "-p", "--providers",
        help = "String of comma separated list of pubkey strings of providers that should belong to this cluster"
    ).required()

    private val governorName by option(
        "-g", "--governor",
        help = "Name of another voter set which can update this cluster."
    ).required()

    private val deployersName by option(
        "-d", "--deployers",
        help = "Name of the voter set which can make updates in this cluster"
    ).required()

    override fun run() {
        val clusterName = when {
            name != "" -> name!!
            autoGenerateClusterName != "" -> autoGenerateClusterName!!
            else -> throw CliError.Companion.CliException(
                "When cluster name is not given, flag -a must be set to " +
                        "autogenerate a cluster name"
            )
        }
        CliExecution(BaseClientConfig.fromPropertiesFile(nodeConfig)).addCluster(
            clusterName,
            providers,
            governorName,
            deployersName
        )
        println("Cluster $name has been added successfully")
    }

}