package net.postchain.mc.cli.cluster

import com.beust.jcommander.Parameter
import com.beust.jcommander.Parameters
import net.postchain.mc.cli.base.CliError
import net.postchain.mc.cli.base.CliResult
import net.postchain.mc.cli.base.CommandBase
import net.postchain.mc.cli.base.Ok
import net.postchain.mc.cli.common0.CliExecution

@Parameters(commandDescription = "Create a new cluster that can hold containers with blockchains.")
class CommandAddCluster : CommandBase() {

    @Parameter(
            names = ["-n", "--name"],
            description = "Name of new cluster")
    private var name = ""

    @Parameter(
            names = ["-a", "--auto-generate-name"],
            description = "Set if cluster name should be autogenerated (suppressed by -n)")
    private var autoGenerateClusterName = false

    @Parameter(
            names = ["-p", "--providers"],
            description = "String of comma separated list of pubkey strings of providers that should belong to this cluster")
    private var providers = ""

    @Parameter(
            names = ["-g", "--governor"],
            description = "Name of another voter set which can update this cluster.",
            required = true)
    private var governorName = ""

    @Parameter(
            names = ["-d", "--deployers"],
            description = "Name of the voter set which can make updates in this cluster",
            required = true)
    private var deployersName = ""

    override fun key(): String = "add-cluster"

    override fun execute(): CliResult {
        return try {
            var resName = ""
            if (name == "") {
                if (autoGenerateClusterName) {
                    resName = autoGenerateName()
                } else {
                    throw CliError.Companion.CliException("When cluster name is not given, flag -a must be set to " +
                            "autogenerate a cluster name")
                }
            } else if (isAlphanumeric(name) and (name.length <= NAME_LENGTH_MAX)) {
                resName = name
            } else {
                throw CliError.Companion.CliException("Invalid cluster name. [Only 0-9A-Za-z] is allowed and max length is" +
                        " $NAME_LENGTH_MAX.")
            }
            CliExecution(loadAppConfig()).addCluster(resName, providers, governorName, deployersName)
            Ok("Cluster $name has been added successfully")
        } catch (e: CliError.Companion.CliException) {
            CliError.CommandNotAllowed(message = e.message)
        }
    }

}